KerasJson: my-model-files/lenet5_model.json
KerasH5:   my-model-files/lenet5_weights.h5
OutputDir: my-hls-lenet5
ProjectName: lenet5
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
